import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  BadgeCheck,
  BarChart2,
  BarChart3,
  Building2,
  Calendar,
  ClipboardList,
  Code2,
  Compass,
  Cpu,
  Eye,
  FileText,
  Film,
  Filter,
  Gauge,
  GitBranch,
  Handshake,
  LayoutGrid,
  LayoutTemplate,
  LineChart,
  Link2,
  MapPin,
  Megaphone,
  MessageCircle,
  MousePointer2,
  Newspaper,
  Package,
  Palette,
  PenTool,
  Phone,
  PieChart,
  Radio,
  RefreshCw,
  Rocket,
  Search,
  Share2,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  TrendingUp,
  UserCheck,
  Users,
  Video,
  Wallet,
  Wifi,
  Zap,
  FlaskConical,
  Layers,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  layers: Layers,
  "bar-chart-3": BarChart3,
  "bar-chart-2": BarChart2,
  sparkles: Sparkles,
  "refresh-cw": RefreshCw,
  "trending-up": TrendingUp,
  "file-text": FileText,
  cpu: Cpu,
  "line-chart": LineChart,
  "map-pin": MapPin,
  star: Star,
  "building-2": Building2,
  phone: Phone,
  filter: Filter,
  "shopping-bag": ShoppingBag,
  "link-2": Link2,
  calendar: Calendar,
  search: Search,
  "code-2": Code2,
  "shield-check": ShieldCheck,
  gauge: Gauge,
  megaphone: Megaphone,
  "flask-conical": FlaskConical,
  "message-circle": MessageCircle,
  users: Users,
  "layout-grid": LayoutGrid,
  radio: Radio,
  "pen-tool": PenTool,
  wallet: Wallet,
  video: Video,
  wifi: Wifi,
  package: Package,
  target: Target,
  eye: Eye,
  "thumbs-up": ThumbsUp,
  "alert-triangle": AlertTriangle,
  "user-check": UserCheck,
  compass: Compass,
  palette: Palette,
  rocket: Rocket,
  handshake: Handshake,
  "git-branch": GitBranch,
  newspaper: Newspaper,
  "share-2": Share2,
  "pie-chart": PieChart,
  "badge-check": BadgeCheck,
  "clipboard-list": ClipboardList,
  film: Film,
  activity: Activity,
  zap: Zap,
  "mouse-pointer-2": MousePointer2,
  "layout-template": LayoutTemplate,
};

export function ServiceBenefitIcon({ name, className }: { name: string; className?: string }) {
  const Icon = map[name] ?? Sparkles;
  return <Icon className={className} aria-hidden />;
}
